local simpleJson = require "SimpleJson"
local lines = 
[[
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
.........--.........
......--............
...--...............
..........G...A.....
####################
]]
--getmetatable('').__index = function(str, i) return string.sub(str, i, i) end
function getStrIndex(str, i)
    return string.sub(str, i, i)
end
local arr = {}
for i in string.gmatch(lines, ".-\n") do
    table.insert(arr, i)
end
--print(simpleJson:encode(arr), #arr)
return arr
